# -*- coding: utf-8 -*-
"""DeitaryLabels Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H--0HUrn-c8I8fQ7TTktj-MxcVVjPZD7
"""

import numpy as np
import pandas as pd

df=pd.read_csv('/content/en.openfoodfacts.org.products.tsv (1).zip', sep='\t')

df.head()

columns_to_drop = ['url','creator','created_t','last_modified_t','generic_name','packaging','packaging_tags','brands','brands_tags','categories','categories_tags','categories_en','origins','origins_tags','manufacturing_places','manufacturing_places_tags','labels','labels_tags','labels_en','emb_codes','emb_codes_tags','first_packaging_code_geo','cities','cities_tags','purchase_places','stores','countries','countries_tags','countries_en','ingredients_from_palm_oil_n','ingredients_from_palm_oil','ingredients_from_palm_oil_tags','ingredients_that_may_be_from_palm_oil_n','ingredients_that_may_be_from_palm_oil','ingredients_that_may_be_from_palm_oil_tags','pnns_groups_2','pnns_groups_1','states','states_tags','states_en','main_category','main_category_en','image_url','image_small_url']
df = df.drop(columns=[col for col in columns_to_drop if col in df.columns])

df.head()

df.isnull().sum()

for cols in df.columns:
  if df[cols].dtype=='object':
    df[cols]=df[cols].fillna(df[cols].mode() [0])
  else:
    df[cols]=df[cols].fillna(df[cols].mean())

df.isnull().sum()

df=df.drop(columns=['glycemic-index_100g','water-hardness_100g'])

df.isnull().sum()

df=df.drop(columns=['chlorophyl_100g'])

df.isnull().sum()

df.isnull().values.any()

df.isnull().sum()[df.isnull().sum() > 0]

columns_to_drop = ['no_nutriments','nutrition_grade_uk','-butyric-acid_100g','-caproic-acid_100g','-lignoceric-acid_100g','-cerotic-acid_100g','-melissic-acid_100g','-elaidic-acid_100g','-mead-acid_100g','-erucic-acid_100g','-nervonic-acid_100g']
df = df.drop(columns=[col for col in columns_to_drop if col in df.columns])

df.head()

df.isnull().values.any()

df.duplicated()

def clean(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z\s]', ' ', text)
    return text

from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer( max_features=10000,
    ngram_range=(1,2),
    stop_words='english')
x=tfidf.fit_transform(df['ingredients_text'])

df.columns

cols = ['product_name', 'ingredients_text', 'allergens',
        'allergens_en', 'traces', 'traces_tags']

for c in cols:
    df[c] = df[c].fillna('').astype(str)

df['full_text'] = (
    df['product_name'] + ' ' +
    df['ingredients_text'] + ' ' +
    df['allergens'] + ' ' +
    df['allergens_en'] + ' ' +
    df['traces'] + ' ' +
    df['traces_tags']
).str.lower()

#sugar free
df['sugar_free'] = df['full_text'].apply(
    lambda x: 0 if 'sugar' in x else 1
)

#vegan
df['vegan'] = df['full_text'].apply(
    lambda x: 0 if any(w in x for w in [
        'milk','egg','honey','butter','cheese',
        'fish','meat','beef','chicken','pork'
    ]) else 1
)

#glutenfree
df['gluten_free'] = df['full_text'].apply(
    lambda x: 0 if any(w in x for w in ['wheat','barley','rye','malt','gluten']) else 1
)

#lactosefree
df['lactose_free'] = df['full_text'].apply(
    lambda x: 0 if any(w in x for w in ['milk','lactose','cream','cheese','butter','yogurt']) else 1
)

#vegetarian
df['vegetarian'] = df['full_text'].apply(
    lambda x: 0 if any(w in x for w in [
        'fish','meat','beef','chicken','pork'
    ]) else 1
)

#oragnic
df['organic'] = df['full_text'].apply(
  lambda x: 1 if 'organic' in x else 0
)

#halal
df['halal'] = df['full_text'].apply(
    lambda x: 1 if 'halal' in x else 0
)

#Non-Gmo
df['non_gmo'] = df['full_text'].apply(
    lambda x: 1 if ('non gmo' in x or 'non-gmo' in x or 'nongmo' in x) else 0
)

label_cols = [
    'gluten_free', 'lactose_free', 'sugar_free',
    'vegan', 'vegetarian', 'organic',
    'halal', 'non_gmo'
]

Y = df[label_cols]

from sklearn.preprocessing import LabelEncoder

label_columns = [
    'product_name','quantity','allergens','allergens_en',
    'traces','created_datetime','last_modified_datetime'
]

for col in label_columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col].astype(str))

from sklearn.model_selection import train_test_split
X=df['full_text']
y=Y

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=42)

from sklearn.svm import LinearSVC
from sklearn.multiclass import OneVsRestClassifier
from sklearn.feature_extraction.text import TfidfVectorizer

# Initialize TfidfVectorizer
vectorizer = TfidfVectorizer(
    max_features=10000,
    ngram_range=(1,2),
    stop_words='english'
)

# Vectorize X_train and X_test
X_train_vectorized = vectorizer.fit_transform(X_train)
X_test_vectorized = vectorizer.transform(X_test)

svm_clf = OneVsRestClassifier(LinearSVC(dual=True)) # Removed solver='liblinear'
svm_clf.fit(X_train_vectorized, y_train)

pred = svm_clf.predict(X_test_vectorized)

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, pred)
print("Accuracy:", accuracy)

from sklearn.metrics import f1_score

f1 = f1_score(y_test, pred, average='micro')
print("F1-score (micro):", f1)

# Save the trained model and vectorizer
import joblib
joblib.dump(svm_clf, 'diet_model.pkl')
joblib.dump(vectorizer, 'tfidf.pkl')

from sklearn.metrics import hamming_loss, f1_score

# y_true , y_pred → your real & predicted labels

# Hamming Loss
hl = hamming_loss(y_test, pred)

# F1-macro
f1_macro = f1_score(y_test, pred, average='macro')

print("Hamming Loss:", hl)
print("F1 Macro:", f1_macro)

def get_ingredients(food_name):
    row = df[df['product_name'].str.contains(food_name, case=False)]
    if len(row) == 0:
        return ""
    return row.iloc[0]['ingredients_text']

# Save cleaned DF (includes all preprocessed columns like full_text, product_name, ingredients_text)
df.to_pickle('/content/cleaned_food_data.pkl', compression='gzip')  # Smaller file ~200-300MB
print("Cleaned DF saved! Shape:", df.shape)

# You already have df, full_text, model, vectorizer in memory → just load them again safely
import pandas as pd, joblib

# If df disappeared because of restart, reload the original once (60 sec) — otherwise skip this line
# Remove the # below ONLY if you get "name 'df' is not defined"
# df = pd.read_csv('/content/en.openfoodfacts.org.products.tsv (1).zip', sep='\t', low_memory=False)

svm_clf = joblib.load('diet_model.pkl')
vectorizer = joblib.load('tfidf.pkl')

# Quick fix if product_name became index numbers (this happened to you)
if df['product_name'].dtype == 'int64' or df['product_name'].astype(str).str.isnumeric().all():
    print("Fixing broken product_name column...")
    # Re-load correct product_name from the original file (fast trick)
    temp = pd.read_csv('/content/en.openfoodfacts.org.products.tsv (1).zip',
                       usecols=['code', 'product_name'], sep='\t', low_memory=False)
    temp['code'] = temp['code'].astype(str)
    df = df.reset_index(drop=True)
    temp = temp.reset_index(drop=True)
    # Match by row position (works because both files have same order)
    df['product_name'] = temp['product_name']

print("Ready! App launching in next cell...")

!pip install -q gradio==4.44.0 websockets==12.0 --force-reinstall

import pandas as pd
import joblib

try:
    df = pd.read_pickle('/content/cleaned_food_data.pkl', compression='gzip')
    print("Cleaned DF loaded! Shape:", df.shape)
    print("Key columns:", [col for col in ['product_name', 'ingredients_text', 'full_text'] if col in df.columns])
except Exception as e:
    print("DF load failed:", str(e))
    raise  # Stop if failed

try:
    svm_clf = joblib.load('diet_model.pkl')
    vectorizer = joblib.load('tfidf.pkl')
    print("Model loaded OK!")
except Exception as e:
    print("Model load failed:", str(e))
    raise

# ← RUN THIS CELL FIRST (takes 15 seconds)
!pip install -q --upgrade --force-reinstall \
    gradio==4.44.0 \
    huggingface_hub==0.25.1 \
    websockets==12.0 \
    fastapi==0.110.2 \
    uvicorn==0.30.6 \
    --no-deps > /dev/null 2>&1

print("All package conflicts destroyed!")

import pandas as pd, joblib, gradio as gr

# FIX THE BROKEN product_name column (this is the root cause)
print("Fixing product names...")
original = pd.read_csv('/content/en.openfoodfacts.org.products.tsv (1).zip',
                       sep='\t', usecols=['code', 'product_name'], low_memory=False)

# Make sure both dataframes have same order
df = df.reset_index(drop=True)
original = original.reset_index(drop=True)

# OVERWRITE the broken product_name with the REAL one
df['product_name'] = original['product_name'].fillna('Unknown Product')

# Reload model
svm_clf = joblib.load('diet_model.pkl')
vectorizer = joblib.load('tfidf.pkl')

label_names = ['Gluten-Free','Lactose-Free','Sugar-Free','Vegan','Vegetarian','Organic','Halal','Non-GMO']

def predict(food):
    if not food.strip():
        return "Click an example", ""

    matches = df[df['product_name'].astype(str).str.contains(food, case=False, na=False)]
    if len(matches) == 0:
        return "Not found", "But examples below work"

    row = matches.iloc[0]
    ingredients = str(row['ingredients_text']) if pd.notna(row['ingredients_text']) else "No ingredients"
    # Corrected line: If the ingredients string is very short (like "No "), assume no ingredients are listed.
    if len(ingredients) <= 3:
        ingredients = "No ingredients listed"

    pred = svm_clf.predict(vectorizer.transform([str(row['full_text'])]))[0]
    result = "\n".join(f"{n}: {'YES' if p==1 else 'NO'}" for n,p in zip(label_names,pred))

    return f"Found: {row['product_name']}\n\nIngredients:\n{ingredients[:950]}...", result

# 100% REAL examples that exist right now
examples = [
    ["Banana Chips Sweetened"], ["Peanuts"], ["Lotus Organic Brown Jasmine Rice"],
    ["Organic Salted Nut Mix"], ["Organic Polenta"], ["Breadshop Honey Gone Nuts Granola"],
    ["Organic Long Grain White Rice"], ["Organic Muesli"], ["Organic Raw Pumpkin Seeds"],
    ["Dark Chocolate Bar"], ["Nutella"], ["Maggi"]
]

with gr.Blocks(theme=gr.themes.Soft()) as demo:
    gr.Markdown("# Food Label Predictor — NOW FIXED & WORKING")
    gr.Markdown("**Click any example → it works 100%**")
    inp = gr.Textbox(label="Search Product", placeholder="Click example below")
    btn = gr.Button("Check", variant="primary")
    out1 = gr.Textbox(label="Product + Ingredients", lines=12)
    out2 = gr.Textbox(label="Diet Labels", lines=12)
    gr.Examples(examples, inp)
    btn.click(predict, inp, [out1, out2])
    inp.submit(predict, inp, [out1, out2])

demo.launch(share=True)

# deployment is remaining